### ISSUE TITLE
why save un and pw in separate variables?

### ISSUE THREAD

**Issue by y2kbugger** [mart00n/tutorial#3]
in the file tutorial/master/loopsifthen1.py
why dont you use a data structure more appropriate for the task, such as https://docs.python.org/3.4/library/stdtypes.html#dict

**Comment by y2kbugger** [comment]
Any progress on this? This _issue_ has really been _bugging_ me.

**Comment by mart00n** [comment]
Latest commit to loopsifthen1.py has dictionary object. Future development will take place in new file "simpleshell.py". Project will have distinction between groups of users and admin user, with restricted commands.
